changed the indentation from 4 to 2 spaces

diff --git a/bash_template b/bash_template
--- a/bash_template
+++ b/bash_template
@@ -2,40 +2,39 @@
 
 
 print_usage () {
-    echo "Usage: ${G_PROGNAME} <option> arg";
-    echo "    arg: arg description";
-    echo "";
-    echo "  Options:";
-    echo "    -d: Debug mode.";
-    echo "    -h: Print out this message.";
-
-    return 0;
+  echo "Usage: ${G_PROGNAME} <option> arg";
+  echo "    arg: arg description";
+  echo "";
+  echo "  Options:";
+  echo "    -d: Debug mode.";
+  echo "    -h: Print out this message.";
+  
+  return 0;
 }
 
 
 # main () {
-    G_DEBUG_MODE='OFF';
-    readonly G_PROGNAME=`basename $0`;
-    
-    while getopts dh opts; do
-        case ${opts} in
-            d) readonly G_DEBUG_MODE='ON';
-               ;;
-            h) print_usage;
-               exit 0;;
-            *) print_usage;
-               exit 0;;
-        esac
-    done
-    shift `expr ${OPTIND} - 1`
-
-    readonly G_DEBUG_MODE;
-
-    if [ $# -ne 1 ]; then
-        echo "ERROR: Wrong number of arguments.";
-        print_usage;
-        exit 1;
-    fi
-
-    exit 0;
+  G_DEBUG_MODE='OFF';
+  readonly G_PROGNAME=`basename $0`;
+  
+  while getopts dh opts; do
+    case ${opts} in
+      d) readonly G_DEBUG_MODE='ON';;
+      h) print_usage;
+         exit 0;;
+      *) print_usage;
+         exit 0;;
+    esac
+  done
+  shift `expr ${OPTIND} - 1`
+  
+  readonly G_DEBUG_MODE;
+  
+  if [ $# -ne 1 ]; then
+    echo "ERROR: Wrong number of arguments.";
+    print_usage;
+    exit 1;
+  fi
+  
+  exit 0;
 # } main ()
