Added comments, error messages and removed all wget output.

diff --git a/get_zp_content_from_url b/get_zp_content_from_url
--- a/get_zp_content_from_url
+++ b/get_zp_content_from_url
@@ -9,20 +9,25 @@
 #
 ###############################################################
 
-URL=${1}
-PROG_NAME=`basename $0`
-WGET_OPT="-U \"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2.13) Gecko/20101203 Firefox/3.6.13\"";
-
+URL=${1};
+PROG_NAME=`basename $0`;
 if [ -z "${URL}" ]; then
-	echo "Usage ${PROG_NAME} <ZP HTTP URL>"
-	exit 1
+	echo "Usage ${PROG_NAME} <ZP HTTP URL>\n";
+	exit 1;
 fi
 
+# Pretend to be a real browser
+WGET_OPT="-U \"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2.13) Gecko/20101203 Firefox/3.6.13\"";
+
 # Download the html file for parsing.
-TMP_DIR=/tmp
-HTML_FILE_NAME=`echo ${URL} | sed -re 's/.+\///'`
-OUTPUT_HTML_FILE=${TMP_DIR}/${HTML_FILE_NAME}
-wget "${WGET_OPT}" -q ${URL} -O ${OUTPUT_HTML_FILE}
+TMP_DIR=/tmp;
+HTML_FILE_NAME=`echo ${URL} | sed -re 's/.+\///'`;
+OUTPUT_HTML_FILE=${TMP_DIR}/${HTML_FILE_NAME};
+wget "${WGET_OPT}" -q ${URL} -O ${OUTPUT_HTML_FILE};
+if [ $? -ne 0 ]; then
+	echo "ERROR: Failed to download ${URL}.\n";
+	exit 1;
+fi
 
 # The HTML file downloaded contains a java script file which
 # contains the config for the flash media player.
@@ -34,6 +39,10 @@ rm ${OUTPUT_HTML_FILE}
 JS_FILE=`echo ${JS_URL} | sed -re 's/.+\///'`
 OUTPUT_JS_FILE=${TMP_DIR}/${JS_FILE}
 wget "${WGET_OPT}" -q ${JS_URL} -O ${OUTPUT_JS_FILE}
+if [ $? -ne 0 ]; then
+	echo "ERROR: Failed to download ${JS_URL}.\n";
+	exit 1;
+fi
 
 # I suck at regexp, so I'm just going to go through the file
 # until I find the correct mp4 URI.
@@ -49,8 +58,11 @@ while [ ${CAN_EXIT} -eq 0 ]; do
 done
 
 CONTENT_URL=${CONTENT_URL}mp4
-echo ${CONTENT_URL}
 rm ${OUTPUT_JS_FILE}
 
 # Download the mp4 file and save it in a sortable file name.
-wget "${WGET_OPT}" ${CONTENT_URL} -O zp_${HTML_FILE_NAME}.mp4
+wget "${WGET_OPT}" -q ${CONTENT_URL} -O zp_${HTML_FILE_NAME}.mp4
+if [ $? -ne 0 ]; then
+	echo "ERROR: Failed to download ${CONTENT_URL}.\n";
+	exit 1;
+fi
